<?php
	class model_blog{
		public $fields= array();
		public $nullable= array();
		public $default_value= array();
		public $ID= 0;
		public $KEY= "";

		function model_blog($ID=0){
			$this->ID = $ID;
			$this->KEY = "id";
			$this->fields["id"]="int(11)";
			$this->nullable["id"]="NO";
			$this->default_value["id"]="";
			$this->fields["category_id"]="int(11)";
			$this->nullable["category_id"]="NO";
			$this->default_value["category_id"]="";
			$this->fields["title"]="varchar(255)";
			$this->nullable["title"]="NO";
			$this->default_value["title"]="";
			$this->fields["tag_ids"]="varchar(500)";
			$this->nullable["tag_ids"]="NO";
			$this->default_value["tag_ids"]="";
			$this->fields["short_info"]="varchar(1000)";
			$this->nullable["short_info"]="NO";
			$this->default_value["short_info"]="";
			$this->fields["image"]="varchar(100)";
			$this->nullable["image"]="NO";
			$this->default_value["image"]="";
			$this->fields["detail_image"]="varchar(100)";
			$this->nullable["detail_image"]="NO";
			$this->default_value["detail_image"]="";
			$this->fields["description"]="text";
			$this->nullable["description"]="NO";
			$this->default_value["description"]="";
			$this->fields["slug"]="varchar(255)";
			$this->nullable["slug"]="NO";
			$this->default_value["slug"]="";
			$this->fields["meta_title"]="varchar(255)";
			$this->nullable["meta_title"]="NO";
			$this->default_value["meta_title"]="";
			$this->fields["meta_keywords"]="text";
			$this->nullable["meta_keywords"]="NO";
			$this->default_value["meta_keywords"]="";
			$this->fields["meta_desc"]="text";
			$this->nullable["meta_desc"]="NO";
			$this->default_value["meta_desc"]="";
			$this->fields["status"]="enum('Active','Inactive')";
			$this->nullable["status"]="NO";
			$this->default_value["status"]="Active";
			$this->fields["added_date"]="varchar(255)";
			$this->nullable["added_date"]="NO";
			$this->default_value["added_date"]="";
			$this->fields["sort_order"]="int(11)";
			$this->nullable["sort_order"]="NO";
			$this->default_value["sort_order"]="";
			$this->fields["head_code"]="text";
			$this->nullable["head_code"]="NO";
			$this->default_value["head_code"]="";
			$this->fields["body_code"]="text";
			$this->nullable["body_code"]="NO";
			$this->default_value["body_code"]="";
			$this->fields["entry_date"]="varchar(100)";
			$this->nullable["entry_date"]="NO";
			$this->default_value["entry_date"]="";
			$this->fields["entry_date_time"]="varchar(100)";
			$this->nullable["entry_date_time"]="NO";
			$this->default_value["entry_date_time"]="";
			$this->fields["chat_code"]="text";
			$this->nullable["chat_code"]="NO";
			$this->default_value["chat_code"]="";
		}
	}
?>